language: rust
before_script:
- if [[ "$TRAVIS_OS_NAME" != 'linux' ]]; then choco install msys2; refreshenv; pacman -S perl openssl-devel pkg-config; fi
- rustup component add clippy
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo clippy
rust:
- nightly
matrix:
  fast_finish: true
os:
  - linux
  - windows
env:
  global:
    - secure: Rb6sh3M1HPWo3qecefZ37lJ3Dm3EmzOSbRWRT4TmIDTDL5nMYF83N3Qfgb9e/mLlPNg3dmLM9hMJUOaOWJywdPcaTLxoCXXz/mUzPgs3MA3JfdvMyXXfH/FabgnKb+ZGXYwubgVzkonOwbeqYsGElnwX65C2ZxEEkfkYBx+WEhsIDo4C1TGa/bbSwTEOXpLDlvYm46jStMBy/3ss1Bkrn2KVmP4WJOc5r6A2G5u8ytWW+PWoRSGu308d0agcUD3lFguxAbDFXbq0zVtS1bRsB8YJ4k+JKa3Uc8JS0diDKOjh3TMUgfktWxIxB6efAHTp4HsZmWfu1B2l+RmzqYe4Kelwe4YMh7CI0V5T3JJasXJFcs/b25SrX3msIrrb2YtIfRMrG75U4CICHJA5DW/SttCmSj5WJS/YlSorkq4nXmwrZgYqAXyKVS0MCJOLh/LqHKgODrxFFLr/v9FsRe9XdGhTGLsbxIcs0wqUIUsCVtwh3whaFHJ8qQZYnq/Ay4BAgN6Man//di7l9CnsLSK1oUXkJR0VBUSE+E7Lm/0qyi8UbOeOvN57e4H50pPesabQJn/f7w/sRSNLEPzqiaSLT7HWBZ3zwm2F1atunSDTkt0rKhlw6W4hhSczXOn8BL+JSi4f3A6SPSLNYZLTaaDDWp7h3FJIkiQ2gEVd7ogQtKs=
    - secure: vnjIQAAVzCkDBNtNf9z2ZSnA20wGIadYROaYacIWp0zP5iFRObp6SZCTR9qw4lXffo5y1uu8+uWmS6nlIJbaIIr1+4AZPrSy7iTHjZfILznonSLKqBI7w013f9ASTeDOIwkeTRNpg8DahvyTNHsiGlLVyOSneCeE6CXp+d5fD65N2ztB+G+KXDPv+HVTZCMvav0qDxGz/wpCo9xZNxP+Iwt2TrXSrL8L8H9KdJGSpzsHuWWP3poNn7+ni41aSPwEbFm6HliZz+I1bb028isPeGQViQzV3A43t2Ah0sS9FIbWIVYZsf541BqS3U9CnkzQhGHYBQx5LasvZ60i9TGez1xDIQZAsrHKwM5puB8r7IDOYaWzmzQt7uSF5qJepDuGfB86K8wW6SrtjQ9ZorSLrberC640eGVcjhY1JCaGjJz+StI5rcg+Qpj9jFXRzJ9SP/8xoFp/3z4K/TkfwaV/EzyKw70/EfB63D46h8zQp7Sck1qfffewgCQn+A/Qhh1AS6UgkDTtK4SbXcm/jWANPjY+s7j6ZfqcWszD7ONV1QPFNLLYk7F0MRvC4TLq+ceesYSYIgZVsgA3RMoGV3rQbd0u+phABNaDkWGDqXfyL0XUOojSRgh2wqOVS+q5NfjJm7hSVeM20VdKfOEsi5LG2T2j2pMco5Rw5r0ZNIXUJok=
    - secure: Z/xNxgOwn7fEYvyELQJVcEijz6gLIttt4XjsXbUv/TFbZczzbn5/gZHaXdyyOIwJhfo/qe5Bpvq3iCLWK7HJEu1xgFV3c62oKcOyhlPRzjt1BW/j1VDitvK5/xXX5HBVp6VoGSFgo+dM6e0GOVLG4EyxHq4Exlj2/FHSWGvnXUP+Dtcfej1BDVUdm57KYSrmDtttFafYRsetSRGHM+AEhT3XgJMm84/Ba7phEw+HgWMm8OacNEXONsH1hn9wwt1SKcmiQYxewai2nPSZixzneOCCjvIEcN2TnVsSx7VbwsM61okAXxiv883EAckHtTEa3v5FGPjAJGNiEXgpXD2VI5xqlCfCwTn7tci4BWKMHpj+J+W8qgs+WEw/tnfG74y+GapThgqbycUR9Mr8/H3GJfkup2M6A0sYQw0s2mbtfo004VebUCDYAs5IG+tn2oVx6MUbe53efugnPaJWow3VQYhpB3CBMmbuIkz3vEvrWXYlcqcWhTZY0pLRfXOjXnvBdnNFus/O5+r2S28qlkkMwniKFVPydQkMeTihENre/UcxSps0a8w1+3qroBmRTSqtYc09YDm9kBIt1vl0LV8CdJTGabA83i/u/Oc681w+Nx9ZUsqHcXk2cRTdmw93fdTif5Nkres3Ib1jQOFBzQJmPyMtTR2fTRaiJYi80g0Tp2M=
