language: rust
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - nightly
matrix:
  fast_finish: true
cache: cargo