[package]
name = "graph-rs-sdk"
version = "0.0.2"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph Api Client"

exclude = [
    "test_files/*",
    "tests/*",
    "examples/*",
    "test-tools/*",
    "graph-codegen/*"
]
keywords = ["onedrive", "graph", "API"]

[workspace]
members = [
    "graph-oauth",
    "graph-error",
    "test-tools",
    "graph-codegen",
    "graph-http",
    "graph-core",

    "examples/common"
]

[dependencies]
async-std = "1"
async-trait = "0.1"
base64 = "0.13"
futures = "0.3"
handlebars = "2.0.2" # TODO: Update to 4
reqwest = { version = "0.11", features = ["json", "blocking", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
strum = { version = "0.21", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2"

graph-oauth = { path = "./graph-oauth", version = "0.0.2" }
graph-http = { path = "graph-http", version = "0.0.2" }
graph-error = { path = "./graph-error", version = "0.0.1" }
graph-core = { path = "./graph-core", version = "0.0.1" }

[dev-dependencies]
from_as = "0.1"
lazy_static = "1.4"
regex = "1"
warp = "0.3"

graph-codegen = { path = "./graph-codegen", version = "0.0.1" }
test-tools = { path = "./test-tools", version = "0.0.1" }
examples-common = { path = "./examples/common" }

[badges]
travis-ci = { repository = "https://github.com/sreeise/graph-rs", branch = "master" }

[profile.release]
debug = false
