[package]
name = "rust-onedrive"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"
# To be removed when the project is more stable.
publish = false
exclude = [
    "test_files/*",
    "tests/*",
    "examples/*",
    "drive_test_tools/*"
]
keywords = ["onedrive", "graph", "API"]

[workspace]
members = [
    "graph-oauth",
    "graph-error",
    "transform-request",
    "derive_from_to_file",
    "drive-test-tools",
]

[dependencies.url]
git = "https://github.com/servo/rust-url"
features = ["query_encoding"]

[dependencies]
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
serde-transcode = "1.1.0"
reqwest = "0.9.6"
encoding = "0.2.33"
notify = "4.0.0"
base64 = "0.10.1"
strum_macros = "0.14.0"
strum = "0.14.0"
openssl-sys = "0.9"
openssl = { version = "^0.10", features = ["vendored"] }
transform-request = { path = "./transform-request" }
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
derive_from_to_file = { path = "./derive_from_to_file" }

[dev-dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]

[dev-dependencies]
rocket = "0.4.0"
rocket_codegen = "0.4.0"
serde = "1.0.81"
serde_json = "1.0.33"
serde_derive = "1.0.81"
reqwest = "0.9.6"
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
drive-test-tools = { path = "./drive-test-tools" }

[badges]
travis-ci = { repository = "https://github.com/sreeise/rust-onedrive", branch = "master" }

[profile.release]
debug = false