[package]
name = "graph-rs"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"
# To be removed when the project is more stable.
publish = false
exclude = [
    "test_files/*",
    "tests/*",
    "examples/*",
    "test-tools/*"
]
keywords = ["onedrive", "graph", "API"]

[workspace]
members = [
    "graph-oauth",
    "graph-error",
    "test-tools",
]

[dependencies]
url = "1.7.2"
url_serde = "0.2.0"
serde = "1.0.88"
serde_json = "1.0.38"
serde_yaml = "0.8.9"
serde_derive = "1.0.88"
reqwest = "0.9.6"
strum_macros = "0.14.0"
strum = "0.14.0"
openssl-sys = "0.9"
rayon = "1.0.3"
getset = "0.0.7"
log = "0.4"
pretty_env_logger = "0.3"
openssl = { version = "^0.10", features = ["vendored"] }
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
from_as = { git = "https://github.com/sreeise/from_as" }

[dependencies.graph-rs-types]
git = "https://github.com/sreeise/graph-rs-types"
features = ["option"]

[dev-dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]

[dev-dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
serde = "1.0.81"
serde_json = "1.0.33"
serde_derive = "1.0.81"
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
test-tools = { path = "./test-tools" }
criterion = "0.2"

[badges]
travis-ci = { repository = "https://github.com/sreeise/graph-rs", branch = "master" }

[profile.release]
debug = false

[[bench]]
name = "oauth"
harness = false
