[package]
name = "graph-rs"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"

exclude = [
    "test_files/*",
    "tests/*",
    "examples/*",
    "test-tools/*",
    "graph-codegen/*"
]
keywords = ["onedrive", "graph", "API"]

[workspace]
members = [
    "graph-oauth",
    "graph-error",
    "test-tools",
    "graph-codegen",
    "graph-http",
    "graph-core",
]

[dependencies]
url = "2.1.1"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
serde_yaml = "0.8.9"
reqwest = { version = "0.10", features = ["json", "blocking", "stream"] }
strum_macros = "0.14.0"
strum = "0.14.0"
rayon = "1.0.3"
log = "0.4"
base64 = "0.10.1"
pretty_env_logger = "0.3"
handlebars = "2.0.2"
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
graph-http = { path = "./graph-http" }
graph-core = { path = "./graph-core" }
tokio = { version = "0.2.21", features = ["full"] }
async-std = "1.6.0"
async-trait = "0.1.35"
futures = "0.3.5"

[dev-dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]

[dev-dependencies]
rocket = "0.4.2"
rocket_codegen = "0.4.2"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
lazy_static = "1.4.0"
graph-oauth = { path = "./graph-oauth" }
graph-error = { path = "./graph-error" }
graph-core = { path = "./graph-core" }
test-tools = { path = "./test-tools" }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
from_as = { git = "https://github.com/sreeise/from_as" }
graph-codegen = { path = "./graph-codegen" }
graph-http = { path = "graph-http" }
regex = "1"

[badges]
travis-ci = { repository = "https://github.com/sreeise/graph-rs", branch = "master" }

[profile.release]
debug = false

