[package]
name = "graph-core"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"

[dependencies]
strum = { version = "0.19", features = ["derive"] }
Inflector = "0.11.4"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
