[package]
name = "graph-core"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph Api Client"
publish = false

[dependencies]
strum = { version = "0.19", features = ["derive"] }
Inflector = "0.11.4"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
