[package]
name = "test-tools"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph Api Client"
publish = false

[dependencies]
url = "2.1.1"
graph-rs = { path = "../" }
graph-error = { path = "../graph-error" }
rand = "0.6.5"
from_as = { git = "https://github.com/sreeise/from_as" }
serde = "1.0.101"
serde_json = "1.0.38"
serde_derive = "1.0.88"
toml = "0.5"
lazy_static = "1.4.0"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
graph-http = { path = "../graph-http" }
