[package]
name = "graph-error"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
# To be removed when the project is more stable.
publish = false

[dependencies]
reqwest = "0.9.6"
serde = "1.0.101"
serde_json = "1.0.38"
serde_yaml = "0.8.9"
serde_derive = "1.0.88"
base64 = "0.10.1"
url = "1.7.2"
hyper = "0.12.33"