[package]
name = "graph-error"
version = "0.0.1"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Graph Api error types and handling for the graph-rs project"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
handlebars = "2.0.2"
hyper = "0.14"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ring = "0.16.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
url = "2"
