[package]
name = "graph-error"
version = "0.0.1"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Graph Api error types and handling for the graph-rs project"

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "^1.0"
serde_yaml = "0.8.9"
serde_derive = "^1.0"
base64 = "0.10.1"
url = "2.1.1"
hyper = "0.12.33"
snafu = "0.5.0"
tokio = { version = "0.2.21", features = ["full"] }
ring = "0.16.15"
handlebars = "2.0.2"
