[package]
name = "graph-error"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"

[dependencies]
reqwest = "0.9.6"
serde = "^1.0"
serde_json = "^1.0"
serde_yaml = "0.8.9"
serde_derive = "^1.0"
base64 = "0.10.1"
url = "1.7.2"
hyper = "0.12.33"
snafu = "0.5.0"
from_as = { git = "https://github.com/sreeise/from_as" }