[package]
name = "graph-codegen"
version = "0.0.1"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph Api Client"
publish = false

[dependencies]
serde = { version = "1.0.110", features = ["derive", "rc"] }
serde_json = "1.0.53"
serde_derive = "^1.0"
serde_yaml = "0.8.9"
from_as = { git = "https://github.com/sreeise/from_as", version = "0.1.0" }
regex = "1"
Inflector = "0.11.4"
reqwest = { version = "0.10", features = ["json", "blocking", "stream"] }
# graph-http = { version = "0.0.1", path = "../graph-http" }
# graph-core = { version = "0.0.1", path = "../graph-core" }
graph-http = "0.0.1"
graph-core = "0.0.1"
bytes = "0.5.6"
lazy_static = "1.4.0"
rayon = "1.5.0"
strum = { version = "0.19", features = ["derive"] }
