[package]
name = "graph-http"
version = "0.0.1"
authors = ["sreeise <reeisesean@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph Api Client"
publish = false

[dependencies]
url = { version = "2.1.1", features = ["serde"] }
percent-encoding = "2.1.0"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
serde_yaml = "0.8.9"
serde_derive = "^1.0"
reqwest = { version = "0.10", features = ["json", "blocking", "stream"] }
handlebars = "2.0.2"
tokio = { version = "0.2.21", features = ["full"] }
async-std = "1.6.0"
async-trait = "0.1.35"
futures = "0.3.5"
# graph-error = { version = "0.0.1", path = "../graph-error" }
# graph-core = { version = "0.0.1", path = "../graph-core" }
graph-error = "0.0.1"
graph-core = "0.0.1"
bytes = "0.5.6"
pretty_env_logger = "0.3"
log = "0.4"
