[package]
name = "graph-http"
version = "0.0.2"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Http client and utilities for the graph-rs project"

[dependencies]
url = { version = "2", features = ["serde"] }
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
serde_derive = "1"
reqwest = { version = "0.11", features = ["json", "blocking", "stream", "multipart"] }
handlebars = "2.0.2"
tokio = { version = "1", features = ["full"] }
async-std = "1.6.0"
async-trait = "0.1.35"
futures = "0.3"
graph-error = { version = "0.0.1", path = "../graph-error" }
graph-core = { version = "0.0.1", path = "../graph-core" }
# graph-error = "0.0.1"
# graph-core = "0.0.1"
bytes = "1"

[features]
default = ["nightly"]
nightly = []