[package]
name = "graph-oauth"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
# To be removed when the project is more stable.
publish = false

[dependencies.url]
git = "https://github.com/servo/rust-url"
features = ["query_encoding"]

[dependencies]
reqwest = "0.9.6"
serde = "1.0.88"
serde_json = "1.0.38"
serde_yaml = "0.8.9"
serde_derive = "1.0.88"
base64 = "0.10.1"
strum_macros = "0.14.0"
strum = "0.14.0"
rust-crypto = "0.2.36"
openssl = "0.10.19"
webbrowser = "0.4.0"
chrono-humanize = "0.0.11"
chrono = { version = "0.4.6", features = ["serde"] }
rayon = "1.0.3"
derive_from_to_file = { path = "../derive_from_to_file" }
graph-error = { path = "../graph-error" }
transform-request = { path = "../transform-request" }