[package]
name = "graph-oauth"
version = "0.0.1"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph api oauth client for the graph-rs project"

[dependencies]
url = "1.7.2"
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde = { version = "1.0.110", features = ["derive"] }
serde-aux = "*"
serde_json = "1.0.53"
serde_yaml = "0.8.9"
serde_derive = "^1.0"
base64 = "0.10.1"
strum_macros = "0.14.0"
strum = "0.14.0"
webbrowser = "0.4.0"
chrono-humanize = "0.0.11"
chrono = { version = "0.4.6", features = ["serde"] }
# graph-error = { version = "0.0.1", path = "../graph-error" }
graph-error = "0.0.1"
from_as = { git = "https://github.com/sreeise/from_as", version = "0.1.0" }
ring = "0.16.15"
