[package]
name = "graph-oauth"
version = "0.0.2"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph api oauth client for the graph-rs project"

[dependencies]
url = "2"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde-aux = "2"
serde_json = "1"
serde_yaml = "0.8"
base64 = "0.13"
strum = { version = "0.21", features = ["derive"] }
webbrowser = "0.4.0"
chrono-humanize = "0.0.11"
chrono = { version = "0.4.6", features = ["serde"] }
graph-error = { version = "0.0.1", path = "../graph-error" }
# graph-error = "0.0.1"
# from_as = { git = "https://github.com/sreeise/from_as", version = "0.1.0" }
from_as = "0.1.0"
ring = "0.16.15"
