[package]
name = "graph-oauth"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
# To be removed when the project is more stable.
publish = false

[dependencies]
url = "1.7.2"
percent-encoding = "1.0.1"
reqwest = "0.9.6"
serde = "1.0.88"
serde_json = "1.0.38"
serde_yaml = "0.8.9"
serde_derive = "1.0.88"
base64 = "0.10.1"
strum_macros = "0.14.0"
strum = "0.14.0"
openssl = { version = "^0.10", features = ["vendored"] }
webbrowser = "0.4.0"
chrono-humanize = "0.0.11"
chrono = { version = "0.4.6", features = ["serde"] }
derive_from_to_file = { path = "../derive_from_to_file" }
graph-error = { path = "../graph-error" }
from_to_file = { path = "../from_to_file" }