[package]
name = "graph-oauth"
version = "0.0.2"
authors = ["sreeise"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sreeise/graph-rs"
description = "Microsoft Graph api oauth client for the graph-rs project"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4.6", features = ["serde"] }
chrono-humanize = "0.0.11"
from_as = "0.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ring = "0.16.15"
serde = { version = "1", features = ["derive"] }
serde-aux = "2"
serde_json = "1"
serde_yaml = "0.8"
strum = { version = "0.21", features = ["derive"] }
url = "2"
webbrowser = "0.4.0"

graph-error = { path = "../graph-error" }
